//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotebookRCv001.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string WindowState {
            get {
                return ((string)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string LanguageKey {
            get {
                return ((string)(this["LanguageKey"]));
            }
            set {
                this["LanguageKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65001")]
        public int EncodingCodePage {
            get {
                return ((int)(this["EncodingCodePage"]));
            }
            set {
                this["EncodingCodePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double InputWindowHeight {
            get {
                return ((double)(this["InputWindowHeight"]));
            }
            set {
                this["InputWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double InputWindowWidth {
            get {
                return ((double)(this["InputWindowWidth"]));
            }
            set {
                this["InputWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double InputWindowTop {
            get {
                return ((double)(this["InputWindowTop"]));
            }
            set {
                this["InputWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double InputWindowLeft {
            get {
                return ((double)(this["InputWindowLeft"]));
            }
            set {
                this["InputWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HomeCurrentDirectoryOpen {
            get {
                return ((string)(this["HomeCurrentDirectoryOpen"]));
            }
            set {
                this["HomeCurrentDirectoryOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HomeCurrentDirectorySave {
            get {
                return ((string)(this["HomeCurrentDirectorySave"]));
            }
            set {
                this["HomeCurrentDirectorySave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double FolderBrowserDialogHeight {
            get {
                return ((double)(this["FolderBrowserDialogHeight"]));
            }
            set {
                this["FolderBrowserDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double FolderBrowserDialogWidth {
            get {
                return ((double)(this["FolderBrowserDialogWidth"]));
            }
            set {
                this["FolderBrowserDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double FolderBrowserDialogTop {
            get {
                return ((double)(this["FolderBrowserDialogTop"]));
            }
            set {
                this["FolderBrowserDialogTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double FolderBrowserDialogLeft {
            get {
                return ((double)(this["FolderBrowserDialogLeft"]));
            }
            set {
                this["FolderBrowserDialogLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
            set {
                this["WorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SearchForFilesColumnsWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchForFilesColumnsWidth"]));
            }
            set {
                this["SearchForFilesColumnsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string FontFamilyName {
            get {
                return ((string)(this["FontFamilyName"]));
            }
            set {
                this["FontFamilyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string FontWeightName {
            get {
                return ((string)(this["FontWeightName"]));
            }
            set {
                this["FontWeightName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double FontSize {
            get {
                return ((double)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string FontStyleName {
            get {
                return ((string)(this["FontStyleName"]));
            }
            set {
                this["FontStyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string TextDecoration {
            get {
                return ((string)(this["TextDecoration"]));
            }
            set {
                this["TextDecoration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string NormalFontFamily {
            get {
                return ((string)(this["NormalFontFamily"]));
            }
            set {
                this["NormalFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5,0,0,0")]
        public string NormalLineSpacing {
            get {
                return ((string)(this["NormalLineSpacing"]));
            }
            set {
                this["NormalLineSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double NormalFontSize {
            get {
                return ((double)(this["NormalFontSize"]));
            }
            set {
                this["NormalFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string NormalFontStyle {
            get {
                return ((string)(this["NormalFontStyle"]));
            }
            set {
                this["NormalFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string NormalFontWeight {
            get {
                return ((string)(this["NormalFontWeight"]));
            }
            set {
                this["NormalFontWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NormalTextDecoration {
            get {
                return ((string)(this["NormalTextDecoration"]));
            }
            set {
                this["NormalTextDecoration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string NormalForeground {
            get {
                return ((string)(this["NormalForeground"]));
            }
            set {
                this["NormalForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color NormalFontBackground {
            get {
                return ((global::System.Drawing.Color)(this["NormalFontBackground"]));
            }
            set {
                this["NormalFontBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MyForeground {
            get {
                return ((global::System.Drawing.Color)(this["MyForeground"]));
            }
            set {
                this["MyForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color MyFontBackground {
            get {
                return ((global::System.Drawing.Color)(this["MyFontBackground"]));
            }
            set {
                this["MyFontBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5,0,0,0")]
        public string LineSpacing {
            get {
                return ((string)(this["LineSpacing"]));
            }
            set {
                this["LineSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color MyBackground {
            get {
                return ((global::System.Drawing.Color)(this["MyBackground"]));
            }
            set {
                this["MyBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MyMessagesFirstStart {
            get {
                return ((bool)(this["MyMessagesFirstStart"]));
            }
            set {
                this["MyMessagesFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MyMessagesWindowHeight {
            get {
                return ((double)(this["MyMessagesWindowHeight"]));
            }
            set {
                this["MyMessagesWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double MyMessagesWindowWidth {
            get {
                return ((double)(this["MyMessagesWindowWidth"]));
            }
            set {
                this["MyMessagesWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double MyMessagesWindowLeft {
            get {
                return ((double)(this["MyMessagesWindowLeft"]));
            }
            set {
                this["MyMessagesWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double MyMessagesWindowTop {
            get {
                return ((double)(this["MyMessagesWindowTop"]));
            }
            set {
                this["MyMessagesWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string MyMessagesWindowState {
            get {
                return ((string)(this["MyMessagesWindowState"]));
            }
            set {
                this["MyMessagesWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SelectWindowHeight {
            get {
                return ((double)(this["SelectWindowHeight"]));
            }
            set {
                this["SelectWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double SelectWindowWidth {
            get {
                return ((double)(this["SelectWindowWidth"]));
            }
            set {
                this["SelectWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double SelectWindowLeft {
            get {
                return ((double)(this["SelectWindowLeft"]));
            }
            set {
                this["SelectWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double SelectWindowTop {
            get {
                return ((double)(this["SelectWindowTop"]));
            }
            set {
                this["SelectWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string SelectWindowState {
            get {
                return ((string)(this["SelectWindowState"]));
            }
            set {
                this["SelectWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectWindowFirstStart {
            get {
                return ((bool)(this["SelectWindowFirstStart"]));
            }
            set {
                this["SelectWindowFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double SelectAndPasteWindowHeight {
            get {
                return ((double)(this["SelectAndPasteWindowHeight"]));
            }
            set {
                this["SelectAndPasteWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public double SelectAndPasteWindowWidth {
            get {
                return ((double)(this["SelectAndPasteWindowWidth"]));
            }
            set {
                this["SelectAndPasteWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double SelectAndPasteWindowLeft {
            get {
                return ((double)(this["SelectAndPasteWindowLeft"]));
            }
            set {
                this["SelectAndPasteWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double SelectAndPasteWindowTop {
            get {
                return ((double)(this["SelectAndPasteWindowTop"]));
            }
            set {
                this["SelectAndPasteWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string SelectAndPasteWindowState {
            get {
                return ((string)(this["SelectAndPasteWindowState"]));
            }
            set {
                this["SelectAndPasteWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectAndPasteWindowFirstStart {
            get {
                return ((bool)(this["SelectAndPasteWindowFirstStart"]));
            }
            set {
                this["SelectAndPasteWindowFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectAndPasteWindowDirectory {
            get {
                return ((string)(this["SelectAndPasteWindowDirectory"]));
            }
            set {
                this["SelectAndPasteWindowDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DisplayProgressHeight {
            get {
                return ((double)(this["DisplayProgressHeight"]));
            }
            set {
                this["DisplayProgressHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DisplayProgressWidth {
            get {
                return ((double)(this["DisplayProgressWidth"]));
            }
            set {
                this["DisplayProgressWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DisplayProgressTop {
            get {
                return ((double)(this["DisplayProgressTop"]));
            }
            set {
                this["DisplayProgressTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DisplayProgressLeft {
            get {
                return ((double)(this["DisplayProgressLeft"]));
            }
            set {
                this["DisplayProgressLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayProgressFirstStart {
            get {
                return ((bool)(this["DisplayProgressFirstStart"]));
            }
            set {
                this["DisplayProgressFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double DocumentTreeHeight {
            get {
                return ((double)(this["DocumentTreeHeight"]));
            }
            set {
                this["DocumentTreeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double DocumentTreeWidth {
            get {
                return ((double)(this["DocumentTreeWidth"]));
            }
            set {
                this["DocumentTreeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double DocumentTreeTop {
            get {
                return ((double)(this["DocumentTreeTop"]));
            }
            set {
                this["DocumentTreeTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double DocumentTreeLeft {
            get {
                return ((double)(this["DocumentTreeLeft"]));
            }
            set {
                this["DocumentTreeLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DocumentTreeFirstStart {
            get {
                return ((bool)(this["DocumentTreeFirstStart"]));
            }
            set {
                this["DocumentTreeFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string DocumentTreeState {
            get {
                return ((string)(this["DocumentTreeState"]));
            }
            set {
                this["DocumentTreeState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double TextEditorHeight {
            get {
                return ((double)(this["TextEditorHeight"]));
            }
            set {
                this["TextEditorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double TextEditorWidth {
            get {
                return ((double)(this["TextEditorWidth"]));
            }
            set {
                this["TextEditorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double TextEditorLeft {
            get {
                return ((double)(this["TextEditorLeft"]));
            }
            set {
                this["TextEditorLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double TextEditorTop {
            get {
                return ((double)(this["TextEditorTop"]));
            }
            set {
                this["TextEditorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string TextEditorState {
            get {
                return ((string)(this["TextEditorState"]));
            }
            set {
                this["TextEditorState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextEditorFirstStart {
            get {
                return ((bool)(this["TextEditorFirstStart"]));
            }
            set {
                this["TextEditorFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FileUploader_ListViewColumnsWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileUploader_ListViewColumnsWidth"]));
            }
            set {
                this["FileUploader_ListViewColumnsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color MyHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["MyHighlightColor"]));
            }
            set {
                this["MyHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SetColorsForQuickAccess {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SetColorsForQuickAccess"]));
            }
            set {
                this["SetColorsForQuickAccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DirectoryPathWithDownloadedFiles {
            get {
                return ((string)(this["DirectoryPathWithDownloadedFiles"]));
            }
            set {
                this["DirectoryPathWithDownloadedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double PopUpTextBoxWidth {
            get {
                return ((double)(this["PopUpTextBoxWidth"]));
            }
            set {
                this["PopUpTextBoxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double PopUpTextBoxHeight {
            get {
                return ((double)(this["PopUpTextBoxHeight"]));
            }
            set {
                this["PopUpTextBoxHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double PopUpTextBoxLeft {
            get {
                return ((double)(this["PopUpTextBoxLeft"]));
            }
            set {
                this["PopUpTextBoxLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double PopUpTextBoxTop {
            get {
                return ((double)(this["PopUpTextBoxTop"]));
            }
            set {
                this["PopUpTextBoxTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopUpTextBoxFirstRun {
            get {
                return ((bool)(this["PopUpTextBoxFirstRun"]));
            }
            set {
                this["PopUpTextBoxFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncryptPathtoLastFileOpen {
            get {
                return ((string)(this["EncryptPathtoLastFileOpen"]));
            }
            set {
                this["EncryptPathtoLastFileOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncryptPathtoLastFileSave {
            get {
                return ((string)(this["EncryptPathtoLastFileSave"]));
            }
            set {
                this["EncryptPathtoLastFileSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncryptPathtoLastDirectoryOpen {
            get {
                return ((string)(this["EncryptPathtoLastDirectoryOpen"]));
            }
            set {
                this["EncryptPathtoLastDirectoryOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncryptPathtoLastDirectorySave {
            get {
                return ((string)(this["EncryptPathtoLastDirectorySave"]));
            }
            set {
                this["EncryptPathtoLastDirectorySave"] = value;
            }
        }
    }
}
